@URL = http://localhost:4000

# @URL = https://gentle-retreat-23209.herokuapp.com
@TYPE = /api/admin

###
POST  {{URL}}{{TYPE}}/addAdmin
Content-Type: application/json

 {
        "adminName":"ananth text",
        "age":25,
        "email":"sree.kannan",
        "phone":"9042141018"
}

###
GET  {{URL}}{{TYPE}}/getAdmin
Content-Type: application/json

###
GET  {{URL}}{{TYPE}}/getAdminByMail?email=sree.kannan@rapidqube.com
Content-Type: application/json
###
PUT {{URL}}{{TYPE}}/updateAdminByMail/newmail@gmailcom/sree.kannan@rapidqube.com
Content-Type: application/json
###
DELETE {{URL}}{{TYPE}}/deletAdminById/5e55225650b379682c1cd8e9
Content-Type: application/json
