@URL = http://localhost:4000

# @URL = https://gentle-retreat-23209.herokuapp.com
@TYPE = /api/general

###
POST  {{URL}}{{TYPE}}/addProduct
Content-Type: application/json

{
        "name":"Onion",
        "status": true,
        "category": "category-a",
        "vendor":"vendor-a",
        "description":"some description for cooking cream",
        "sku":"SKU",
        "reserved": 2
}

###
GET  {{URL}}{{TYPE}}/getProduct
Content-Type: application/json

###
GET  {{URL}}{{TYPE}}/getProductName
Content-Type: application/json

###
POST  {{URL}}{{TYPE}}/addCategory
Content-Type: application/json

{
        "name":"Cleaning3"
}

###
GET  {{URL}}{{TYPE}}/getCategory
Content-Type: application/json

###

DELETE {{URL}}{{TYPE}}/deleteCategoryId?_id=5e55225650b379682c1cd8e9
Content-Type: application/json
###
POST  {{URL}}{{TYPE}}/addStock
Content-Type: application/json

{
        "openStock":20,
        "usedStock": null,
        "currentStock": 20,
        "_productId": "6059fcd433165c6b341e6bf1"
}

###
GET  {{URL}}{{TYPE}}/getStockDetailsByProductId?_id=605a28e4d71743484010f736
Content-Type: application/json

###
DELETE {{URL}}{{TYPE}}/deleteStockById?_id=605a3184d71743484010f73b
Content-Type: application/json

###